package com.example;

public class App {
    public static void main(String[] args) {
        System.out.println("Hello World from test-java-220005!");
        System.out.println("Generated by Scaffold Forge");
    }
}